enum ProductTag {
  KIDS = "kids",
  ZOD = "zodiaco",
  PET = "pets",
  FOOTWEAR = "calzado",
  RELIGIOUS = "religioso",
  NEON = "neón",
  FANTASY = "fantasía",
  GEMSTONE = "pedrería",
  HANDMADE = "artesanal",
  GOLFY_GOLD = "oro golfy",
  ELEGANT = "elegante",
  CASUAL = "casual",
  FUN = "divertido",
  ECONOMIC = "economico",
  MIYUKI_WEAVING = "tejido miyuki",
  HAMSA = "hamsa",
  MOSTACILLA = "mostacilla",
  EVIL_EYE = "ojo turco",
  COLORFUL = "colorido",
  ETHNIC = "étnico",
  RUSTIC = "rústico",
  AGED = "envejecido",
  SHINY = "brillante",
  YOUTH = "juvenil",
}
export default ProductTag;
